- .argocd/service.yaml
- cms/Dockerfile
> fix: database service

- .argocd/configmap.yaml
- .argocd/deployment.yaml
- .argocd/ingress.yaml
- .argocd/volume.yaml
> chore: Update MySQL configmap and volume storage.

- .argocd/volume.yaml
> fix: update storage capacity to 5Gi

- .argocd/service.yaml
> fix: changed database port from 3306 to 5432.

- .argocd/deployment.yaml
- .argocd/ingress.yaml
- .argocd/service.yaml
- push.sh
> feat: add deployment and service for bff container

- .argocd/deployment.yaml
- .argocd/volume.yaml
> chore: add persistent storage for CMS uploads

- .argocd/deployment.yaml
- .argocd/volume.yaml
> chore: change volume name

- .argocd/deployment.yaml
- .argocd/volume.yaml
> fix: change k8s  volume

- .argocd/volume.yaml
> fix: change k8s volumeName

- anitection/lib/main.dart
- anitection/lib/screens/animal_room/animal_room_screen.dart
動物のプロフィール画面のダイアログ部分の実装を行いました。
APIとの繋ぎ込みは行っていません。　
https://www.figma.com/file/c4y1uSC90BowFtnzW9nSiG/%E3%81%82%E3%81%AB%E3%81%A6%E3%81%8F%E3%81%97%E3%82%87%E3%82%93?type=design&node-id=73-4088&mode=design&t=UgipnoIX5QJEda4A-0
Closed #25
> 動物のプロフィール画面のダイアログ部分の実装を行いました

- .github/workflows/deploy.yml
> fix: add environment variables for CMS deployment

- .github/workflows/deploy.yml
> fix: update Docker build arguments for cms

- cms/Dockerfile
> fix: add environment variables to Dockerfile

- cms/Dockerfile
> fix: add environment variables for database

- bff/config/env.go
- bff/interface/handler/strapi_handler.go
> fix: refactor environment variable loading and error

- cms/src/api/animal/content-types/animal/schema.json
- cms/src/extensions/users-permissions/content-types/user/schema.json
- cms/types/generated/contentTypes.d.ts
アニマルのテーブルに毛の長さと大きさを追加した
また。ユーザーテーブルに地域を追加した
> chore: update animal and user schema

- cms/src/api/animal-kind/content-types/animal-kind/schema.json
- cms/src/api/pedigree/content-types/pedigree/schema.json
- cms/src/api/pedigree/controllers/pedigree.js
- cms/src/api/pedigree/documentation/1.0.0/pedigree.json
- cms/src/api/pedigree/routes/pedigree.js
- cms/src/api/pedigree/services/pedigree.js
- cms/types/generated/contentTypes.d.ts
> feat: add pedigree API files

- bff/interface/handler/strapi_handler.go
> fix: add Authorization header to requests

- bff/interface/handler/strapi_handler.go
> fix: refactor Strapi handler to include Authorization

- bff/interface/handler/strapi_handler.go
bffにapplication/jsonがないとputがうまく動かなかった。。
> fix: bffのヘッダーにapplication/jsonを追加した

- bff/interface/handler/strapi_handler.go
> fix: application/jsonを追加した時の修正

- bff/interface/handler/strapi_handler.go
> fix: ヘッダー取得するように修正

- cms/src/api/message/content-types/message/schema.json
- cms/src/api/notification/content-types/notification/schema.json
- cms/types/generated/contentTypes.d.ts
> chore: update 既読用のデータを追加した

- web/src/components/atoms/Text.tsx
- web/src/components/organisms/AnimalDetail.tsx
- web/src/components/organisms/AnimalList.tsx
- web/src/components/organisms/Login.tsx
- web/src/components/organisms/NotificationList.tsx
- web/src/components/organisms/Register.tsx
- web/src/components/pages/Institution.tsx
- web/src/components/pages/Send.tsx
- web/src/components/pages/Setting.tsx
- web/src/components/templates/Modal.tsx
> chore: change ui
